# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

zeebe.client:
  #broker.gatewayAddress: 127.0.0.1:26500
  #security.plaintext: true
  cloud:
    region: bru-2
    clusterId: <replace-with-your-value>
    clientId: RrEGoDkP_IakJlLXj~eB9XIkFvzQ6Ac-
    clientSecret: <replace-with-your-value>
zeebe:
  client:
    job:
      timeout: 30000
